name: iosApp
options:
  bundleIdPrefix: com.stabilar
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stabilar.iosapp
        INFOPLIST_FILE: iosApp/Info.plist
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../shared/build/xcode-frameworks"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-framework"
          - "Shared"
schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
